#!/bin/sh

# Copyright (c) 2008 John Watson. All rights reserved.
# http://photodoto.com/index.php/2008/02/25/tethered-shooting-with-linux/
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#     * Neither the name of the organization nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

CAMERA_FOLDER=/store_00010001

echo "Press CTRL-C to quit.\n";

while [ 1==1 ]
do
	gphoto2 --folder="$CAMERA_FOLDER" --get-all-files --hook-script=view
	gphoto2 --folder="$CAMERA_FOLDER" --delete-all-files --recurse
	sleep 1
done

exit;

#!/bin/bash
# Captures a series of images using gphoto2
# $1: Starting shutter speed (index: 0 = 1/4000, 1 = 1/3200, ...
# $2: Ending shutter speed
# $3: Delay (in seconds) between exposures
# Other example
for ((i=$1; i<=$2; i++))
do
gphoto2 --set-config-index /main/capturesettings/shutterspeed=$i;
gphoto2 --capture-image;
sleep $3;
done
If this is (for example) saved in a file named camerascript.sh, then:


